# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Interface to FLOPART C++ code
#'
#' @param data_vec Integer vector of non-negative count data
#' @param weight_vec Numeric vector of positive weights (same size as data_vec)
#' @param penalty non-negative real-valued penalty (larger for fewer peaks)
#' @param label_type_vec Integer vector of label types
#' @param label_start_vec Integer vector of label starts
#' @param label_end_vec Integer vector of label ends
#' @return List with named elements: cost_mat and intervals_mat (one row for each data point, first column up, second down), segments_df (one row for each segment in the optimal model)
FLOPART_interface <- function(data_vec, weight_vec, penalty, label_type_vec, label_start_vec, label_end_vec) {
    .Call(`_FLOPART_FLOPART_interface`, data_vec, weight_vec, penalty, label_type_vec, label_start_vec, label_end_vec)
}

